# usage generated by chatgpt
# demos can be found at find_rule.py
# -*- coding: utf-8 -*-

# 這個檔案是 API 使用範本（中文註解版）
# 目的：示範如何用現有架構直接呼叫本地分析，不需要瀏覽器。

from __future__ import annotations

from typing import Dict, List, Optional

from fileProcess import playerState, RoundState, States
from analyze import getRound
from mjanalyzer_local import (
    LocalAnalysisResult,
    analyze_round_state,
    analyze_tiles,
    annotate_states_shanten,
    calculate_shanten,
)


# -----------------------------
# 資料結構說明（對應 fileProcess.py）
# -----------------------------
# playerState:
# - tiles: List[str]，例如 "211" 這種原始牌代碼
# - shantenCount: int 上聽數，未計算時通常是 -99
#
# RoundState:
# - stepStr: 該步驟動作文字
# - stepId: 步驟編號
# - player: 長度固定 4 的 playerState 陣列
# - abandonTiles: 已打出的牌（原始代碼）
#
# States:
# - state: List[RoundState]
# - playerBank: 莊家方位（E/S/W/N）
# - winnerLoc: 勝方位（E/S/W/N）
# - get_player(ref, loc): 取該 RoundState 的某方玩家資料
# - player_index_from_loc(loc): 將方位轉 index


def template_load_states(log_file: str) -> States:
    # 載入牌譜檔，回傳 States(含每步驟的上廳數)
    return getRound(log_file)


def template_calc_shanten_only(
    hand_tiles: List[str],
    dead_tiles: Optional[List[str]] = None,
    validate: bool = True,
) -> int:
    # 只算上聽數（最快）
    # hand_tiles/dead_tiles 請用 tile id 格式，例如: "1m", "9s", "3z"
    return calculate_shanten(
        hand_tiles=hand_tiles,
        dead_tiles=dead_tiles or [],
        validate=validate,
    )


def template_analyze_hand_full(
    hand_tiles: List[str],
    dead_tiles: Optional[List[str]] = None,
    validate: bool = True,
) -> LocalAnalysisResult:
    # 分析單一手牌完整資訊
    # 回傳內容包含：shanten/statusText/recommendations/pong/chi/kong/summaryStats
    return analyze_tiles(
        hand_tiles=hand_tiles,
        dead_tiles=dead_tiles or [],
        validate=validate,
    )


def template_analyze_step_views(
    states: States,
    step_idx: int,
    include_winner_view: bool = True,
    validate: bool = False,
) -> Dict[str, LocalAnalysisResult]:
    # 分析某一步，輸出 winner/E/S/W/N 視角（視 include_winner_view 而定）
    if step_idx < 0 or step_idx >= len(states.state):
        raise IndexError(f"step_idx 超出範圍: {step_idx}")

    ref: RoundState = states.state[step_idx]
    return analyze_round_state(
        ref=ref,
        states=states,
        include_winner_view=include_winner_view,
        validate=validate,
    )


def template_fill_all_steps_shanten(states: States, validate: bool = False) -> None:
    # 直接回填所有步驟、四位玩家的 shantenCount
    # 寫入位置：states.state[i].player[j].shantenCount
    annotate_states_shanten(states, validate=validate)


def template_get_player_shanten_series(
    states: States,
    loc: str = "S",
    limit: int = 80,
) -> List[int]:
    # 取得某一家每一步的上聽數序列
    idx = states.player_index_from_loc(loc)
    if idx < 0 or idx >= 4:
        raise ValueError(f"loc 無效或 playerBank 未設定: {loc}")

    out: List[int] = []
    end = min(limit, len(states.state))
    for i in range(end):
        out.append(states.state[i].player[idx].shantenCount)
    return out


def template_print_player_shanten_series(
    states: States,
    loc: str = "S",
    limit: int = 80,
) -> None:
    # 直接印出某一家每一步上聽數
    # 注意：這個函式假設你已先呼叫 template_fill_all_steps_shanten()
    series = template_get_player_shanten_series(states, loc=loc, limit=limit)
    for i, value in enumerate(series):
        print(f"step {i}: {loc} shanten = {value}")


def template_result_to_dict(result: LocalAnalysisResult) -> dict:
    # dataclass -> dict，方便回 API / JSON
    return result.to_dict()


def template_quick_start(log_file: str) -> None:
    # 快速流程範例：載入 -> 回填全步驟上聽 -> 印出南家前 20 步 -> 分析第 10 步東家
    states = template_load_states(log_file)

    # 1) 回填全步驟四家上聽數
    template_fill_all_steps_shanten(states, validate=False)

    # 2) 印出南家前 20 步
    template_print_player_shanten_series(states, loc="S", limit=20)

    # 3) 抓第 10 步做完整分析
    step_idx = min(10, len(states.state) - 1)
    views = template_analyze_step_views(states, step_idx=step_idx, validate=False)
    east_result = views["E"]

    print("------ 第 10 步東家摘要 ------")
    print("statusText:", east_result.statusText)
    print("shanten:", east_result.shanten)
    print("difficulty:", east_result.difficultyScore, east_result.difficultyGrade)
    print("recommendation count:", len(east_result.recommendations))


if __name__ == "__main__":
    # 請改成你的牌譜檔案路徑
    sample_file = "SimCat VS MeowCaTS VS Rowlet VS Dartrix (2025_05_03_23_34_33_8270)-(MeowCaTS(Win))_Win.txt"
    template_quick_start(sample_file)
